.circleci/config.yml

Fix the error:
```
Warning: Your Xcode (9.0) is outdated.
Please update to Xcode 9.0.1 (or delete it).
```

CircleCI: Ignore out-of-date XCode

---

Formula/fwdpp.rb

```
brew linkage fwdpp
System libraries:
/usr/lib/libSystem.B.dylib
/usr/lib/libc++.1.dylib
/usr/lib/libz.1.dylib
Homebrew libraries:
/Users/sjackman/.homebrew/opt/libsequence/lib/libsequence.20.dylib (brewsci/bio/libsequence)
/Users/sjackman/.homebrew/opt/gsl/lib/libgsl.23.dylib (gsl)
/Users/sjackman/.homebrew/opt/gsl/lib/libgslcblas.0.dylib (gsl)
Dependencies with no linkage:
boost
```

fwdpp: Boost is a build dependency

---

Formula/kmc.rb

No linkage to `gcc` and so no run time dependency.
```
❯❯❯ brew linkage kmc
System libraries:
/usr/lib/libSystem.B.dylib
/usr/lib/libbz2.1.0.dylib
/usr/lib/libz.1.dylib
```

kmc: Does not depend on gcc and fix bottle block

---

Formula/emboss.rb
Formula/maker.rb
Formula/raxml.rb
Formula/squeakr.rb
Formula/uniqtag.rb

Hello :-)
The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Accordingly, this PR updates all static DOI links, as you also show [in the CONTRIBUTING.md](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md#citation).
Because I'm touching only comments, I omitted the build tests. Hope this is OK.
-----

Link DOIs to preferred resolver

---

.circleci/config.yml

Reduce the number of default number of make jobs to 8.
The default number of HOMEBREW_MAKE_JOBS on CircleCI for Linux is 32.
The resources available reported by CircleCI are 2 CPU and 4 GB RAM.
32 processes of GCC often exceeds the 4 GB of available memory.
Since our instance has only 2 CPU, it's likely not any faster either.

CircleCI: Set HOMEBREW_MAKE_JOBS=4

---

.circleci/config.yml

Updating these out-of-date taps is slow.

CircleCI: Remove out-of-date taps on macOS

---

.travis.yml

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

TravisCI: Fix brew doctor

---

.circleci/config.yml

Fix Error: Calling `or_later` bottles is deprecated! Use bottles
without `or_later` (or_later is implied now) instead.

CircleCI: Remove --or-later

---

.circleci/config.yml

The previous commit included an unintended "echo".
https://github.com/brewsci/homebrew-bio/pull/556

CircleCI: Unshallow Homebrew/brew repo if needed

---

Formula/parsnp.rb

The other pull request has already been merged, so here is a new one. Or is there a better way?

parsnp: fix any_cellar_relocation

---

Formula/flye.rb

-----
When I do `brew install --HEAD flye` I get 
```
Cloning into '/home/hielke/.cache/Homebrew/flye--git'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
```
The branch name brew should be looking for is "flye". This PR solves that.

flye: add correct branch name

---

Formula/transdecoder.rb

Fix the error:
```
Error: Unsupported type NilClass for nil
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency_collector.rb:107:in `parse_spec'
```
See https://github.com/brewsci/homebrew-bio/issues/414#issuecomment-512593664

transdecoder: Fix Unsupported type NilClass for nil

---

Formula/exonerate.rb

Fix the error:
```
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/gettext/lib/libintl.8.dylib
Referenced from: /usr/local/bin/exonerate
Reason: image not found
```
-----

exonerate: Change cellar to :any

---

.circleci/config.yml

Work around the error:
```
mv: cannot stat 'brew-test-bot.xml': No such file or directory
```
-----
See for example https://github.com/brewsci/homebrew-bio/pull/740

CircleCI: Skip brew-test-bot.xml

---

Formula/gatk.rb

* Update gatk formula from 4.1.3.0 -> 4.1.4.0
-----
I tried to use the script `brew bump-formula-pr` but had problems with it so I just did it manually.  Hopefully that's ok.

Update gatk to 4.1.4.0

---

.circleci/config.yml

Update CIRCLE XCode to 10.3, avoid sierra gcc

---

.circleci/config.yml

c.f. https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions

circle: update to latest Xcode on Mojave

---

Formula/clustal-w.rb

-----
Some people/programs expect clustalw to found in the PATH as clustalw, even if it is version 2. Also apt will install clustalw as just clustalw. That's why I think it is a good idea to have clustalw as an alias/symlink to clustalw2 to avoid any confusion.

Create an alias for clustal-w (clustalw, next to clustalw2)

---

Formula/wiggletools.rb

-----
Fix the error:
```
dyld: Library not loaded: /usr/local/opt/htslib/lib/libhts.2.dylib
Referenced from: /private/tmp/wiggletools-test-20200220-75212-1ymmv7r/test/../bin/wiggletools
Reason: image not found
```

wiggletools: Bump revision for htslib, fix python2

---

.github/workflows/upload-bottles.yml

Use `brew pr-upload` rather than `brew test-bot --ci-upload`.

upload-bottles.yml: Use pr-upload

---

Formula/wiggletools.rb

wiggletools: Remove uses_from_macos "python@2"

---

Formula/gatk.rb

Current usage of brew install brewsci/bio/gatk install (for me, on linuxbrew, not sure on mac)
```
==> Installing gatk from brewsci/bio
Error: No available formula with the name "python@2" (dependency of brewsci/bio/gatk)
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
git -C "$(brew --repo homebrew/core)" fetch --unshallow
python@2 was deleted from homebrew/core in commit 8f8f34572d:
python@2: delete
Closes https://github.com/Homebrew/linuxbrew-core/issues/20091.
Signed-off-by: Michka Popoff <michkapopoff@gmail.com>
To show the formula before removal run:
git -C "$(brew --repo homebrew/core)" show 8f8f34572d^:Formula/python@2.rb
If you still use this formula consider creating your own tap: …
```

Remove python@2 from gatk formula

---

.github/workflows/build-bottles.yml
.github/workflows/upload-bottles.yml

Use Docker image homebrew/ubuntu16.04 rather than homebrew/brew.

.github: Use Docker image homebrew/ubuntu16.04

---

.github/workflows/build-bottles.yml
.github/workflows/upload-bottles.yml

-----
Fixes this issue:
```
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
dirname: missing operand
Try 'dirname --help' for more information.
mkdir: cannot create directory '': No such file or directory
```
Fixed in Homebrew/brew#8009 (Should be included in brew version > 2.4.7)

Use `homebrew/ubuntu16.04:master` to fix #1027

---

Formula/adam.rb

Download URL changed due to Scala 2.12/Spark 3.x build configuration.
-----

adam 0.32.0

---

Formula/cannoli.rb

Download URL changed due to Scala 2.12/Spark 3.x build configuration.
-----

cannoli 0.10.0

---

Formula/shovill.rb

-----
`flash` dependency needs to be updated to `brewsci/bio/flash` since a different formulae with the same name was added to `homebrew/core`

shovill: fix dependencies (# 1082)

---

Formula/fasttree.rb

-----
Formulae that might need to be bumped:
- pirate
- parsnp
- nullarbor
- roary

fasttree: replace gcc dependency with libomp

---

Formula/kat.rb

kat: disable unsupported compiler flags on macOS

---

Formula/ghostz.rb

-----
`libomp` might be required for Linux too; I'm not sure

ghostz: replace gcc with libomp

---

Formula/hisat2.rb

It does not pass spdx check for GPL-3.0, not sure if I should change
-----
This bumps to hisat 2.2.1 and adds hisat2 python scripts
Otherwise we currently get this error
```
hisat2 -x hg38/genome -1 left.fq.gz -2 right.fq.gz > out.sam                                                                                                            ✘ 130
sh: 1: /home/linuxbrew/.linuxbrew/bin/../Cellar/hisat2/2.2.0/bin/hisat2_read_statistics.py: not found
```
It is fixed after this PR

hisat2 2.2.1 and add python scripts

---

Formula/pymol.rb

-----
This is a retry of https://github.com/brewsci/homebrew-bio/pull/1011 with several modifications.
`brew audit` showed some errors as shown below, but I have no idea to fix them. Any help is welcomed.
```
$ brew audit --strict /path/to/pymol.rb
pymol:
* 1: col 1: No Sorbet sigil found in file. Try a `typed: false` to start (you can also use `rubocop -a` to automatically add this).
* 1: col 1: Missing top-level class documentation comment.
* 1: col 1: Missing frozen string literal comment.
* 55: col 3: Assignment Branch Condition size for install is too high. [<3, 36, 2> 36.18/17]
* 55: col 3: Method has too many lines. [22/10]
Error: 5 problems in 1 formula detected
```

pymol: update 2.4.0

---

Formula/seqan@3.rb

--- 
~The last point gave me some issues that I couldn't fix immediately. I would appreciate any help with this:~
<details><summary>CLICK ME</summary>
<p>
```
/u/l/H/L/T/brewsci (master|✔) $ brew audit --strict seqan@3
Fetching gem metadata from https://rubygems.org/.........
Fetching thread_safe 0.3.6
Fetching concurrent-ruby 1.1.7
Fetching minitest 5.14.2
Installing minitest 5.14.2
Installing thread_safe 0.3.6
Installing concurrent-ruby 1.1.7
Fetching zeitwerk 2.4.0
Fetching ast 2.4.1
Installing zeitwerk 2.4.0
Fetching bindata 2.4.8
Installing ast 2.4.1
Using bundler 1.17.3
Fetching byebug 11.1.3
Installing bindata 2.4.8
Fetching json 2.3.1
Installing byebug 11.1.3 with native extensions
Fetching docile 1.3.2
Installing json 2.3.1 with native extensions
Installing docile 1.3.2
Fetching …
```

seqan3 3.0.2

---

Formula/arcs.rb

-----
```console
$ brew audit brewsci/bio/arcs
Missing libraries:
unexpected (/usr/local/lib/gcc/9/libgcc_s.1.dylib)
Broken dependencies:
/usr/local/opt/gcc/lib/gcc/9/libgomp.1.dylib (gcc)
/usr/local/opt/gcc/lib/gcc/9/libstdc++.6.dylib (gcc)
Unexpected missing library linkage detected
brewsci/bio/arcs:
* arcs has broken dynamic library links:
```

arcs: Bump revision for gcc@9

---

Formula/hssp.rb

-----
This is a new formula of hssp. 
I also suggest that `xssp.rb` formula should be deprecated because two programs `mkdssp` and `mkhssp` installed by `brew install xssp` are now managed independently.

hssp 3.1.5 (new formula)

---

Formula/xssp.rb

-----
Version 3.0.10 is the latest stable version before `dssp` was removed and `xssp` was renamed to `hssp`
Related: #1189, #1192

xssp: update to 3.0.10 and deprecate

---

Formula/dsh-bio.rb

-----
Sorry, `brew bump-formula-pr`  didn't work for this update
```
$ brew bump-formula-pr --strict dsh-bio --url= ...
...
brewsci/bio/dsh-bio:
* Formula dsh-bio contains deprecated SPDX licenses: ["LGPL-3.0"].
You may need to add `-only` or `-or-later` for GNU licenses (e.g. `GPL`, `LGPL`, `AGPL`, `GFDL`).
For a list of valid licenses check: https://spdx.org/licenses/
Error: 1 problem in 1 formula detected
Error: `brew audit` failed!
```
`brew audit` on its own also fails for me, though apparently not because of this formula
```
$ brew audit --strict Formula/dsh-bio.rb
Error: undefined method `audit_exceptions' for nil:NilClass
Please report this issue:
https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:183:in `block in audit' …
```

dsh-bio 1.4

---

Formula/xssp.rb

-----
Fixes style error:
```
xssp.rb:10:3: C: bottle (line 10) should be put before deprecate! (line 8)
```

xssp: move `deprecate!` to after `bottle`

---

Formula/abyss-explorer.rb
Formula/artemis.rb
Formula/astral.rb
Formula/bazam.rb
Formula/bbtools.rb
Formula/beast2.rb
Formula/cluster-picker.rb
Formula/dsh-bio.rb
Formula/figtree.rb
Formula/gatk.rb
Formula/gepard.rb
Formula/jspecies.rb
Formula/mhap.rb
Formula/minced.rb
Formula/nextflow.rb
Formula/pathvisio.rb
Formula/pilon.rb
Formula/realphy.rb
Formula/rtg-tools.rb
Formula/sepp.rb
Formula/snpeff.rb
Formula/trimmomatic.rb
Formula/trinity.rb
Formula/varscan.rb
Formula/varsim.rb
Formula/webin-cli.rb

Fix `Calling depends_on :java is deprecated! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.` by changing `depends_on :java` to `depends_on "openjdk"`.
This PR was adapted from https://github.com/brewsci/homebrew-bio/pull/1213. It does not bump revisions, which needs to be done per formula in separate PRs.
- abyss-explorer
- artemis
- astral
- bazam
- bbtools
- beast2
- cluster-picker
- dsh-bio
- figtree
- gatk
- gepard
- jspecies
- mhap
- minced
- nextflow
- pathvisio
- pilon
- realphy
- rtg-tools
- sepp
- snpeff
- trimmomatic
- trinity
- varscan
- varsim
- webin-cli

Depend on openjdk rather than :java

---

Formula/pymol.rb

-----
Build a bottle for `pymol` for macOS Catalina 10.15.

pymol: update 2.4.0 bottle.

---

Formula/phyx.rb

Avoid using unless with multiple conditions
-----

phyx: fix style error

---

Formula/libccp4.rb

-----
Libccp4 is the protein X-ray crystallography toolkit. This is required for clipper and coot.

libccp4 6.5.1 (new formula)

---

Formula/ssm.rb

-----
Secondary-structure matching (SSM), a new tool for fast protein structure alignment. This PR depends on mmdb2 and libccp4, and will be required for Coot.

ssm 1.4 (new formula)

---

Formula/clipper4coot.rb

-----
The formula is set to `clipper4coot` to distinguish from `clipper` (https://formulae.brew.sh/formula/clipper).
This PR includes building and installing fftw2 as its `resource` because it is not currently maintained and formulation of fftw2 is out of Homebrew's policy.

clipper 2.1.20180802 (new formula)

---

Formula/pymol.rb

-----
On M1 Mac, CPPFLAGS `-I#{Formula["freetype"].opt_include}/freetype2` didn't work (https://github.com/brewsci/homebrew-bio/issues/1290). This PR will solve the issue on M1 Mac.

pymol: change CPPFLAGS for M1 Mac

---

Formula/pymol.rb

-----
update python resources to suppress warning messages at startup:
```
/usr/local/Cellar/pymol/2.4.0_1/libexec/lib/python3.9/site-packages/Pmw/Pmw_2_0_1/lib/PmwLoader.py:92: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if k[0] is not '_' and type(v) != types.ModuleType:
```

pymol: update python resources to suppress warnings

---

Formula/pymol.rb

-----
retry updating to build pymol-2.4.0_2 bottles.

pymol: re-update python resources to suppress warnings

---

Formula/mmdb2.rb

-----
add `--enable-shared` option for building coot.

mmdb2: add the enable-shared option

---

Formula/gatk.rb

-----
I've noticed that for some reason I get a new message whenever I do anything like `brew audit` or `brew install` that has a message like this:
```
Error: Failed to load cask: Formula/gatk.rb
Cask 'gatk' is unreadable: wrong constant name #<Class:0x00007faa52059d68>
Warning: Treating Formula/gatk.rb as a formula.
```
It goes away if I specify the `--formula` argument to brew but I'm not sure if there's something that needs to be updated in the formula itself or if it's just a new weird thing that's happening to me.

gatk 4.2.0.0

---

Formula/maxbin2.rb

Use the wrapper script bin/maxbin2 rather than libexec/run_MaxBin.pl.
-----
This PR does not require rebuilding the bottles.

maxbin2: Fix the test

---

Formula/idba.rb

Fix the error:
```
Broken dependencies:
/usr/local/opt/gcc/lib/gcc/9/libgomp.1.dylib (gcc)
/usr/local/opt/gcc/lib/gcc/9/libstdc++.6.dylib (gcc)
Warning: idba has broken dynamic library links
```
Fixes https://github.com/brewsci/homebrew-bio/issues/1303

idba: Bump revision for gcc@9

---

Formula/pymol.rb

-----
Since the pyqt formula has been upgraded to version 6 recently, the dependency `pyqt` should be corrected to `pyqt@5`.

pymol: change pyqt to pyqt@5

---

Formula/biointerchange.rb

Second try. Pull request for @sjackman to check why I can't use `make install`, but `bin.install` works for me (locally).

biointerchange 2.0.5 (new formula)

---

.github/workflows/upload-bottles.yml

-----
Fix the error
```
Error: no `skopeo` and HOMEBREW_FORCE_HOMEBREW_ON_LINUX is set!
```
See https://github.com/brewsci/homebrew-bio/runs/2299025169?check_suite_focus=true#step:5:87
Skopeo is included in Ubuntu 20.10 (Groovy Gorilla), but not in Ubuntu 20.04 LTS (Focal Fossa). Skopeo is included in the GitHub Actions Ubuntu 20.04 VM image.

CI: Use the GitHub Actions VM image for skopeo

---

Formula/pymol.rb

-----
update bottle to use the latest libnetcdf.19.dylib instead of ilibnetcdf.18.dylib.
Please let me know if there is a better way to fix it.

pymol: update bottle to use the latest libnetcdf

---

Formula/pymol.rb

-----
This PR makes the pymol module available in the Homebrew site-packages (the default `PYTHONPATH` for Homebrew's python@3.9) and also adds a test to verify that the module is loadable.

pymol: install pth file to Homebrew site-packages

---

Formula/arcs.rb

-----
When ABySS uses `arcs` it does not require `links` and uses instead `abyss-scaffold`.

arcs: Remove dependency on links-scaffolder

---

Formula/xssp.rb

Fix Error: brewsci/bio/xssp: missing keyword: date
-----
Fixes https://github.com/brewsci/homebrew-bio/issues/1365

xssp: Add deprecation date

---

Formula/ema.rb

-----
This PR fixes the problem of https://github.com/brewsci/homebrew-bio/pull/1185.
Also, This replaces the term "whitelist" with "allowlist" because it is not recommended now and causes a problem on `brew style brewsci/bio`.
```
==> brew style brewsci/bio
==> FAILED
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-bio/Formula/ema.rb:40:18: C: Consider replacing problematic term 'whitelist' with 'allowlist' or 'permit'.
"The barcode whitelist is available at\n#{prefix/"4M-with-alts-february-2016.txt"}"
^^^^^^^^^
```

ema: fix build problem

---

Formula/edirect.rb

-----
update to ver. 15.3.
`ecommon.sh` is now required in the `libexec` directory.

edirect 15.3

---

.github/workflows/build-bottles.yml

Reverts brewsci/homebrew-bio#1400 due to a new issue below.
```
[FIX] Missing permissions in CI
From https://github.com/brewsci/homebrew-bio
* [new ref]         refs/pull/1400/head -> pr-head
pr=1400 sha1=87eb7c5fece7cd39a35841f57423efa2e9482134
run_id=1173580685 artifact_id=87205930
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   275    0   275    0     0    747      0 --:--:-- --:--:-- --:--:--   747
bottles.zip: Zip archive data, at least v2.0 to extract
Archive:  bottles.zip
extracting: bottle_output.txt       
inflating: steps_output.txt        
On …
```

Revert "[FIX] Missing permissions in CI"

---

Formula/mmtf-cpp.rb

-----
Recently, the dependency was updated from `msgpack` to `msgpack-cxx`. see https://github.com/Homebrew/homebrew-core/pull/84334.

mmtf-cpp: change dependency to msgpack-cxx

---

Formula/edirect.rb

-----
edirect 16.2. The version of openssl has been updated to the latest one to pass the installation of IO::Socket::SSL.

edirect 16.2

---

Formula/apbspdb2pqr.rb

-----
Fix an issue https://github.com/brewsci/homebrew-bio/issues/1462. Some Linux distribution support is now dropped as mentioned in https://github.com/brewsci/homebrew-bio/pull/917.

apbspdb2pqr: fix git tag

---

Formula/maxit.rb

-----
Maxit 11.100. This is useful to convert a structure file to pdb or mmCIF format.

maxit 11.100 (new formula)

---

Formula/maxit.rb

-----
fix missing odb files to run maxit completely.

maxit: fix missing odb files

---

Formula/pymol.rb

-----
modified the formula because the latest catch2 v3.0.1 has no <catch2/catch.hpp> and PyMOL 2.5.0 is not compatible now.

pymol: remove catch2 dependency

---

Formula/pymol.rb

-----
Restore dependencies on pyqt@5 and python@3.9.

pymol: restore pyqt@5 and python@3.9

---

Formula/ale.rb

New version; adds support for arm64 architectures, and uses new `install` target in makefile.

---

Formula/rmblast.rb

Bump version.
Add keg_only because rmblast conflicts with blast.
-----

rmblast 2.11.0

---

Formula/raster3d.rb

The original URL is no longer available. The Internet Archive has a copy.
See https://web.archive.org/web/20230000000000*/http://www.bmsc.washington.edu/raster3d/Raster3D_3.0-7.tar.gz

raster3d: Use Internet Archive mirror

---

Formula/hh-suite.rb
Formula/relion.rb

Fix unnecessary escape of spaces using `brew style --fix`.

style: Fix unnecessary escape of spaces

---

Formula/staden-io-lib.rb

staden-io-lib 1.15.0

---

Formula/libsbml.rb

libsbml is a library for handling text files in Systems Biology Markup Language (SBML).
A brief explanation for the additional configuration flags (-DENABLE_FBC=ON -DENABLE_GROUPS=ON):
These enable two optional extensions for the libsbml library, namely "fbc" and "groups". Both are relevant for the research community that uses linear programming to predict metabolic processes in living cells (i.e., flux balance analysis). apt and dnf linux builds also include these two extensions.
-----
This is my first formula. Any feedback is welcome.

libsbml 5.20.2 (new formula)

---

Formula/conform-gt.rb

conform-gt 24May16

---

Formula/kissplice.rb

-----
Kissplice was packaged before the migration to brewsci/bio : https://github.com/brewsci/homebrew-science/blob/master/Formula/kissplice.rb
Modernize packaging with the current configuration :
- gitlab
- modern cmake
- run sample example as test stage. another possibility is running make test in install
Kissplice depends on bcalm, but uses an internal build that is patched to work with ARM MacOS.
The patch has been submitted to bcalm upstream but in the meantime the current bcalm formula does not build on ARM MacOS.
Sadly bcalm embeds the shims directory through the C/C++ compiler path which makes `brew audit` fail.
I have added patches to fix this but this is quite ugly.
In the long run it would be better to do it in the bcalm formula and then depend on it, but this would have to …

kissplice 2.6.5 (new formula)

---

Formula/coot.rb

-----
With removal of dependency on `requests` (Coot >= 1.1.10) the remaining dependencies of `requests` (`charset-normalizer` and `idna`) can also be removed.

coot: no longer need to install Python dependencies of requests

---

Formula/autodock-vina.rb

autodock-vina: fix boost errors

---

Formula/racon.rb

-----
`racon_test` was removed because it depends on buildpath.

racon 1.5.0: remove racon_test

---

Formula/qtltools.rb

qtltools 1.3.1 (new formula)

---

Formula/edirect.rb

edirect 22.4

---

Formula/alphafill.rb

alphafill 2.1.0 (new formula)

---

Formula/libstatgen.rb

This will be needed for [`bamUtil`](https://github.com/statgen/bamUtil), for which I will submit a new formula PR shortly.
-----

libstatgen 1.0.15

---

Formula/ntlink.rb

ntlink 1.3.11

---

Formula/rdkit.rb
Formula/rdkit4coot.rb

-----
RDkit with `-DCOORDGEN_FORCE_BUILD=ON` is required for the correct building of Coot, so add it as `keg_only`.

rdkit4coot 2024.09.1 (new formula)

---

Formula/relion.rb

relion 5.0.0

---

Formula/voronota.rb

This pull request updates the `Formula/voronota.rb` file to streamline dependencies and improve build flag organization. The most important changes include removing unused dependencies and restructuring compiler and linker flags for better clarity and maintainability.
* Removed `boost` and `python` as dependencies, as they are no longer required for the formula. (`[Formula/voronota.rbL20-L23](diffhunk://#diff-48dc80a2cb9eefd17347b460752e589904a52e171413abf3dc588faa50a80ed9L20-L23)`)
* Split `CXXFLAGS` and `LDFLAGS` for macOS builds to improve clarity by separating include paths and linker flags. (`[Formula/voronota.rbL39-R39](diffhunk://#diff-48dc80a2cb9eefd17347b460752e589904a52e171413abf3dc588faa50a80ed9L39-R39)`)
---
-----

voronota: Remove unnecessary dependencies

---

Formula/openstructure.rb

This pull request updates the dependencies for the `Openstructure` formula to align with platform-specific requirements.
Dependency updates:
* [`Formula/openstructure.rb`](diffhunk://#diff-bec696567eb9cc30ed32151e2c39b1adddd4ce6d25c23c588e9e89e6671bb997R46-L47): Replaced `postgresql@15` with `libpq` as a dependency for macOS to streamline compatibility and reduce redundancy.
---
-----

openstructure: Replace a dependency on MacOS

---

Formula/dssp.rb

This pull request updates the `Formula/dssp.rb` file to enhance Python support by adding dependencies and functionality for Python 3.13, including the ability to build and test a Python module. 
* Added `boost-python3` and `python@3.13` as dependencies to support Python 3.13 functionality.
* Introduced a `python3` method to specify the Python version (`python3.13`) used in the formula.
* Modified the `install` method to create the Python site-packages directory, enable building the Python module (`-DBUILD_PYTHON_MODULE=ON`), and ensure proper installation paths.
* Added a test to verify that the Python module (`mkdssp`) can be successfully imported.
---
-----

dssp: Enable Python bindings

---

Formula/libcifpp.rb

This pull request updates the `Formula/libcifpp.rb` file to reflect changes in the `libcifpp` library version, dependencies, and build configuration. The most important changes include updating the library to version 8.0.1, modifying dependency requirements, and enabling shared library builds.
* Updated `url` to point to version 8.0.1 of the `libcifpp` library and updated the corresponding `sha256` checksum.
* Removed the unconditional dependency on `boost` and added a conditional dependency on `boost` for Linux systems only.
* Added the `-DBUILD_SHARED_LIBS=ON` flag to the `cmake` command to enable building shared libraries.
---
-----

libcifpp v8.0.1

---

Formula/gemmi.rb

This pull request updates the `Formula/gemmi.rb` file to enhance the build process and dependencies for the Gemmi formula. Key changes include adding new dependencies, switching to faster libraries, enabling Python module support, and improving installation and testing steps.
- Added new build dependencies: `nanobind`, `ninja`, and `robin-map`. Also added runtime dependencies: `python3` and `zlib-ng` (replacing `zlib` for better performance).
- Updated the `install` method to enable Python module support (`USE_PYTHON=ON`) and set the Python installation directory dynamically based on the Python version. Switched the build system to use Ninja for faster builds. [[1]](diffhunk://#diff-8b615d05c2a2e9926ac7b94fd38dcf985842078b7ff6b6e595162e25d974e1f4L17-R37) …

gemmi: Enable python bindings

---

Formula/hyphy.rb

Updates HyPhy to version 2.5.78.
- Updated version from 2.5.63 to 2.5.78
- Updated SHA256 checksum to `06bef149fbcdfd1692f6c01e1246e99e120513a041126c5bbc4c46960a18d141`
---
*This PR updates HyPhy to the latest stable release.*

hyphy: update to 2.5.78
