brewsci/homebrew-bio

- .travis.yml
Fix the error:
```
/usr/lib/ruby/1.9.1/rubygems/version.rb:191: in `strip!': can't modify frozen String (RuntimeError)
```
> TravisCI: Use rvm: system

- Formula/figtree.rb
> fix bottle section

- Formula/shovill.rb
> shovill 0.9.0

- Formula/artemis.rb
> artemis 17.0.1

- Formula/clustal-w.rb
> fix bottle section i forgot

- Formula/clustal-omega.rb
> add missing 'cite' keyword

- Formula/readseq.rb
> readseq 2.1.30

- .circleci/config.yml
By request of @maplesond in https://github.com/brewsci/homebrew-bio/pull/132#issuecomment-375600514to build `portcullis`
> CircleCI: Increase no_output_timeout to 20m

- Formula/minced.rb
> minced: fix bottle block

- Formula/abricate.rb
> abricate: fix root_url

- Formula/megahit.rb
> megahit: fix bottle section

- Formula/shovill.rb
> shovill 1.0.1

- Formula/gatk.rb
See https://github.com/broadinstitute/gatk/releases/tag/4.0.11.0
> gatk 4.0.11.0

- .github/main.workflow
- Makefile
Create formula.json for Repology.
> Make formula.json

- Formula/kaiju.rb
-----
I'll get around to committing this soon. Just saw it and didn't want to forget.
> kaiju: Fix caveats

- Formula/abyss-explorer.rb
> abyss-explorer: Fix test

- azure-pipelines.yml
> Azure: Use Homebrew/brew rather than Linuxbrew/brew

- .circleci/config.yml
See https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-298/index.html
> circle: use xcode 9.2

- .circleci/config.yml
> Downgrade XCode to 10.2 | High Sierra support

- Formula/gatk.rb
- [ x ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ x ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ x ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ x ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?
-----
> gatk 4.1.4.1

- .github/workflows/build-bottles.yml
> Add .github/workflows/build-bottle.yml

- .github/workflows/upload-bottles.yml
> Add .github/workflows/upload-bottles.yml

- .github/workflows/build-bottles.yml
- Formula/trnascan.rb
> trnascan 2.0.4

- .github/workflows/upload-bottles.yml
- Formula/fasttree.rb
> fasttree 2.1.11

- Formula/arcs.rb
> arcs 1.1.1

- Formula/ntjoin.rb
> ntJoin 1.0.1 (new formula)

- .github/workflows/upload-bottles.yml
> upload-bottles.yml: Publish the uploaded bottles

- Formula/ntcard.rb
> update ntCard to 1.2.0

- Formula/ntcard.rb
> update ntCard to 1.2.1

- Formula/mapcaller.rb
> mapcaller 0.9.9.33

- Formula/racon.rb
> racon 1.4.3

- Formula/astral.rb
> astral 5.7.1

- Formula/busco.rb
> busco: fix config path

- Formula/iqtree.rb
> iqtree 1.6.12

- Formula/kma.rb
> kma 1.2.21

- Formula/kraken.rb
> kraken 1.1.1

- Formula/masurca.rb
-----
Adds new `polca.sh` genome polishing tool
> masurca 3.3.5

- Formula/treepl.rb
> treepl 2018.05.22

- Formula/mapcaller.rb
> mapcaller 0.9.9.34

- Formula/mapcaller.rb
> mapcaller 0.9.9.37

- Formula/busco.rb
> busco 4.0.4

- Formula/blast@2.2.rb
-----
Needed by BUSCO for multithreaded blast searches
> blast@2.2 2.2.31 (new formula)

- Formula/busco.rb
> busco: revision for blast@2.2

- Formula/seqkit.rb
> seqkit-v0.12.0

- Formula/prokka.rb
- Formula/tbl2asn.rb
> prokka 1.14.6 + tbl2asn 25.8

- Formula/abricate.rb
> abricate 0.9.9

- Formula/finch-rs.rb
> finch 0.3.0

- Formula/freebayes.rb
- Formula/snippy.rb
- Formula/snp-sites.rb
> freebayes 1.3.2 + snippy 4.5.0 + snp-sites

- Formula/nullarbor.rb
> nullarbor 2.0.20191013

- Formula/apbspdb2pqr.rb
- Formula/gatk.rb
- Formula/kaiju.rb
- Formula/megahit.rb
- Formula/mir-prefer.rb
- Formula/nxrepair.rb
- Formula/oases.rb
- Formula/quickmerge.rb
- Formula/varsim.rb
- Formula/xmatchview.rb
- apbspdb2pqr
- gatk
- kaiju
- megahit
- mir-prefer
- nxrepair
- oases
- quickmerge
- varsim
- xmatchview
> Fix python@2 dependency

- Formula/roary.rb
> roary 3.13.0

- Formula/libgff.rb
> libgff 1.2

- Formula/vmatch.rb
> vmatch 2.3.1

- Formula/legsta.rb
> legsta 0.5.1

- Formula/megahit.rb
> megahit 1.2.9

- Formula/racon.rb
> racon 1.4.10

- Formula/bifrost.rb
> bifrost 1.0

- Formula/vcf2phylip.rb
> vcf2phylip 2.0

- Formula/lsd2.rb
> Lsd2 1.4.2.2

- Formula/snp-dists.rb
> snp-dists 0.7.0

- Formula/gatk.rb
~~- [  ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?~~
-----
> gatk 4.1.5.0

- Formula/kounta.rb
> kounta 0.2.3

- Formula/gatk.rb
> Gatk make bottle

- Formula/bali-phy.rb
> bali-phy 3.5.0

- Formula/samclip.rb
> samclip 0.3

- Formula/nanopolish.rb
> nanopolish 0.12.0

- .github/workflows/build-bottles.yml
See https://github.com/jonchang/audit-action
> build-bottles.yml: Add jonchang/audit-action

- Formula/samclip.rb
> samclip 0.4.0

- Formula/snippy.rb
> snippy 4.6.0

- Formula/masurca.rb
> masurca 3.3.9

- Formula/skesa.rb
> skesa 2.4.0

- Formula/shovill.rb
> shovill 1.1.0

- Formula/delly.rb
> delly 0.8.3

- Formula/fasta.rb
> fasta 36.3.8h

- Formula/mpboot.rb
> mpboot: revision to fix build

- Formula/bifrost.rb
> bifrost 1.0.3

- Formula/abricate.rb
> abricate 1.0.0

- Formula/ntjoin.rb
> ntjoin 1.0.2

- Formula/infernal.rb
> infernal 1.1.3

- Formula/gatk.rb
> gatk 4.1.6.0

- Formula/discovardenovo.rb
> discovardenovo: Fix case insensitive file systems

- Formula/souporcell.rb
https://github.com/wheaton5/souporcell
https://www.biorxiv.org/content/10.1101/699637v1
> souporcell 2.0 (new formula)

- Formula/ntedit.rb
> ntedit 1.3.2

- Formula/kraken2.rb
> kraken2 2.0.9

- Formula/hh-suite.rb
> hh-suite 3.2.0 (new formula)

- Formula/hh-suite.rb
> hh-suite: Improve style

- Formula/bcalm.rb
See https://github.com/GATB/bcalm/releases/tag/v2.2.2
> bcalm 2.2.2

- Formula/trinity.rb
See https://github.com/trinityrnaseq/trinityrnaseq/releases/tag/v2.8.6
> trinity 2.8.6

- Formula/ntjoin.rb
* Use python@3.8 to be consistent with numpy and scipy formulae
-----
> ntjoin: bump revision

- Formula/easel.rb
> easel 0.46

- Formula/hh-suite.rb
> hh-suite 3.2.0: formula refinement

- Formula/artemis.rb
- Formula/bowtie.rb
- Formula/breseq.rb
- Formula/cd-hit.rb
- Formula/dida.rb
- Formula/easel.rb
- Formula/gatk.rb
- Formula/gepard.rb
- Formula/gzstream.rb
- Formula/jspecies.rb
- Formula/kaiju.rb
- Formula/kent-tools.rb
- Formula/mir-prefer.rb
- Formula/ngmerge.rb
- Formula/nxrepair.rb
- Formula/oases.rb
- Formula/quickmerge.rb
- Formula/taxonkit.rb
- Formula/varsim.rb
- Formula/vcf2phylip.rb
- Formula/wiggletools.rb
- Formula/xmatchview.rb
- artemis
- bowtie
- breseq
- cd-hit
- dida
- easel
- gatk
- gepard
- gzstream
- jspecies
- kaiju
- kent-tools
- mir-prefer
- ngmerge
- nxrepair
- oases
- quickmerge
- taxonkit
- varsim
- vcf2phylip
- wiggletools
- xmatchview
-----
> Fix style of 22 formulae

- .github/workflows/build-bottles.yml
-----
Also add `HOMEBREW_NO_INSTALL_CLEANUP=1`
> build-bottles.yml: Fix jonchang/audit-action

- Formula/bowtie.rb
> bowtie: Use Python 3

- Formula/vcf2phylip.rb
> vcf2phylip: Use Python 3

- Formula/salmon.rb
See https://github.com/COMBINE-lab/salmon/releases/tag/v1.2.0
> salmon 1.2.1

- Formula/hisat2.rb
> hisat2 2.2.0

- Formula/xmatchview.rb
> xmatchview 1.2.3

- Formula/gatk.rb
> gatk 4.1.7.0

- Formula/taxonkit.rb
> taxonkit-0.6.0

- Formula/ivar.rb
> ivar 1.2.2

- Formula/r2r.rb
- Can't do, network problems. Ask CI.
-----
r2r is a thing for drawing nice (I think) looking vector pictures of RNA SSs. It is also a dependency of rscape.
> r2r 1.0.6 (new formula)

- .github/workflows/build-bottles.yml
-----
Fix the error:
```
==> brew doctor
==> FAILED
Warning: You have uncommitted modifications to Homebrew/brew.
Uncommitted files:
?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/byebug-11.1.3/lib/byebug.rb
?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/byebug-11.1.3/lib/byebug/attacher.rb
…
```
See https://github.com/brewsci/homebrew-bio/pull/1009#issuecomment-631628602
> build-bottles.yml: Run brew update-reset on Linux

- Formula/mapcaller.rb
> mapcaller 0.9.9.38

- Formula/pirate.rb
> pirate 1.0.3

- Formula/phlawd.rb
> phlawd: revision for libomp

- Formula/bodr.rb
> bodr 10 (new formula)

- Formula/fastp.rb
https://github.com/OpenGene/fastp/releases/tag/v0.20.1
> fastp 0.20.1

- Formula/stringtie.rb
> stringtie 2.1.3b

- Formula/rasusa.rb
> rasusa 0.3.0

- Formula/gatk.rb
> gatk 4.1.8.0

- Formula/gfakluge.rb
-----
https://github.com/edawson/gfakluge/releases/tag/1.1.2
> gfakluge 1.1.2

- Formula/ntjoin.rb
> ntjoin 1.0.3

- Formula/trinity.rb
https://github.com/trinityrnaseq/trinityrnaseq/releases/tag/v2.9.1
> trinity 2.9.1

- Formula/salmon.rb
https://github.com/COMBINE-lab/salmon/releases/tag/v1.3.0
> salmon 1.3.0

- Formula/seqkit.rb
> seqkit-0.13.0

- Formula/seqkit.rb
> seqkit 0.13.1

- Formula/abricate.rb
-----
Also added `brewsci/bio/` prefix to deps
Related: #1027, #1076
> abricate 1.0.1

- Formula/seqkit.rb
-----
Sorry for these frequently updates.
> seqkit 0.13.2

- Formula/dsh-bio.rb
> dsh-bio 1.3.3

- Formula/fwdpp.rb
> fwdpp: revision bump for gsl

- Formula/nanofilt.rb
-----
Fix style error:
```
C:  7:  3: use the Source url found on PyPI downloads page
```
> nanofilt: update source url (# 1112)

- Formula/cutadapt.rb
-----
Fix style errors:
```
C: 20:  5: use the Source url found on PyPI downloads page
C: 25:  5: use the Source url found on PyPI downloads page
C: 30:  5: use the Source url found on PyPI downloads page
```
> cutadapt: update source urls (# 1113)

- Formula/iqtree.rb
> iqtree 1.6.12 (downgrade)

- Formula/iqtree2.rb
> iqtree2 2.0.6 (new formula)

- Formula/gatk.rb
> upgrade gatk to 4.1.8.1

- Formula/roary.rb
> roary: revision bump for perl

- Formula/unicycler.rb
> unicycler: revision bump for python

- Formula/sga.rb
-----
Fix style error:
```
C: 25: 10: Use a commit hash URL rather than an unstable pull request URL
```
> sga: update patch url

- Formula/canu.rb
-----
Fix style error:
```
C:  4: 12: https://canu.readthedocs.org/en/latest/ should be https://canu.readthedocs.io/en/latest/
```
> canu: update homepage

- Formula/flowcraft.rb
-----
Should fix this error https://github.com/brewsci/homebrew-bio/pull/1119/checks?check_run_id=907969409#step:4:107 in #1119
```
/usr/local/Cellar/python/3.7.4/bin/python3: bad interpreter: No such file or directory
```
> flowcraft: revision bump for python@3.8

- .github/workflows/update-develop.yml
Updates `develop` branch when `master` is pushed to
No-op if `develop` is already updated (e.g. pushing to `master` after uploading bottles for `develop`)
> workflows: add update-develop

- Formula/cd-hit.rb
> cd-hit: replace gcc with libomp

- Formula/e-mem.rb
> e-mem: replace gcc with libomp

- Formula/genome-painter.rb
> genome-painter: replace gcc with libomp

- Formula/bwa-mem2.rb
-----
Not needed for tag/revision formula
> bwa-mem2: delete sha256 stanza

- Formula/biobloomtools.rb
> biobloomtools 2.3.3

- Formula/edirect.rb
> Update edirect formula to version 13.8

- Formula/biobloomtools.rb
- Formula/bwa-mem2.rb
- Formula/cap3.rb
- Formula/humann2.rb
- Formula/magic-blast.rb
- Formula/metaphlan.rb
- Formula/mmtf-cpp.rb
- Formula/mummer.rb
- Formula/quast.rb
- Formula/realphy.rb
- Formula/seqan@3.rb
- Formula/sortmerna.rb
- biobloomtools.rb:3:9: C: Description shouldn't start with the formula name.
- bwa-mem2.rb:2:9: C: Description shouldn't start with an article.
- cap3.rb:3:9: C: Description shouldn't start with the formula name.
- humann2.rb:3:9: C: Description shouldn't start with the formula name.
- magic-blast.rb:2:9: C: Description shouldn't start with the formula name.
- metaphlan.rb:3:9: C: Description shouldn't start with the formula name.
- mmtf-cpp.rb:3:9: C: Description shouldn't start with an article.
- mummer.rb:43:15: C: Avoid immutable Array literals in loops.
- quast.rb:6:9: C: Description shouldn't start with the formula name.
- realphy.rb:3:9: C: Description shouldn't start with an article.
- seqan@3.rb:4:9: C: Description shouldn't start with an article.
- sortmerna.rb:3:9: C: …
> Fix style issues

- Formula/tigmint.rb
> tigmint 1.2.1

- Formula/ntcard.rb
> ntcard 1.2.2

- Formula/raptor.rb
> raptor 1.0.1 (new formula)

- Formula/xmatchview.rb
> xmatchview 1.2.5

- Formula/psmc.rb
> psmc 0.6.5 (new formula)

- Formula/seqkit.rb
> seqkit 0.14.0

- Formula/taxonkit.rb
> taxonkit 0.6.1

- Formula/taxonkit.rb
-----
Sorry for another update in less than 24h. It's a quick bug fix, I want minimize the influence:)
> taxonkit 0.6.2

- Formula/hh-suite.rb
> hh-suite 3.3.0

- Formula/gffcompare.rb
-----
https://github.com/gpertea/gffcompare
This showed up in my `Explore repositories`
> gffcompare 0.12.1 (new formula)

- .github/workflows/build-bottles.yml
-----
Work around the CI failure `Error: Failure while executing; brew uses --include-build --include-test --recursive brewsci/bio/...`
> build-bottles.yml: Add --skip-recursive-dependents

- Formula/bifrost.rb
> bifrost 1.0.5

- Formula/dssp.rb
-----
This is a new formula of dssp, which is related to https://github.com/brewsci/homebrew-bio/pull/1189.
> dssp 3.1.4 (new formula)

- Formula/ntjoin.rb
> ntjoin 1.0.4

- .github/workflows/upload-bottles.yml
> upload-bottles.yml: check for `ci-skip-upload` label

- .github/workflows/upload-bottles.yml
-----
This should fix `[[: not found` error: https://github.com/brewsci/homebrew-bio/runs/1426831000#step:5:53
Also update master even if upload is skipped
> upload-bottles.yml: fix upload skip

- .github/workflows/upload-bottles.yml
-----
I should have Googled the error
https://stackoverflow.com/a/12230723
> `[[` is a bash-builtin. Your `/bin/bash` doesn't seem to be an actual bash.
> Add `#!/bin/bash` at the top of file
Previous attempt: #1208
> upload-bottles.yml: actually fix upload skip

- .github/workflows/upload-bottles.yml
> upload-bottles.yml: set `shell` to `bash`

- Formula/bmdca.rb
-----
This is a new formula of bmDCA (see https://github.com/ranganathanlab/bmDCA).
> bmdca 0.8.12 (new formula)

- Formula/ntjoin.rb
> ntjoin 1.0.5

- Formula/ntedit.rb
> ntedit 1.3.3

- .github/workflows/build-bottles.yml
See https://github.com/Homebrew/brew/pull/9442
and https://github.com/Homebrew/brew/pull/9452
and https://github.com/Homebrew/homebrew-core/pull/66290
> CI: Set HOMEBREW_FORCE_VENDOR_RUBY=1 for macOS

- Formula/tmalign.rb
-----
TMalign is an algorithm for sequence independent protein structure comparisons.
> tmalign 20190822 (new formula)

- Formula/ntedit.rb
> ntedit 1.3.4

- Formula/mican.rb
-----
`mican` is a structure alignment algorithm that can handle Multiple-chain complexes, Inverse direction of secondary structures, Cα only models, Alternative alignments, and Non-sequential alignments.
> mican 20191127 (new formula)

- Formula/raptor.rb
> raptor 1.1.0

- Formula/emboss.rb
Closes https://github.com/brewsci/homebrew-bio/issues/1229
> emboss: always build without x11

- Formula/jmol.rb
based off of https://github.com/brewsci/homebrew-science/blob/aac950a2dc512ab6c7a278355fad234f2175360a/Formula/jmol.rb
-----
> jmol 14.31.2 (new formula)

- Formula/bodr.rb
- Formula/pplacer.rb
- Formula/treepl.rb
- Formula/trimadap.rb
- Formula/varscan.rb
-----
<table><tr><th>Before</th><th>After</th></tr>
<tr>
<td>
<pre>
bodr : 10 ==> 5-1
pplacer : 1.1.alpha17 ==> 1.0.r031
treepl : 2018.05.22 ==> 1.0
trimadap : 0.1.11 ==> 0.1
varscan : 2.4.3 ==> 2.4.2
</pre>
</td>
<td>
<pre>
bodr : 10 ==> 10
pplacer : 1.1.alpha17 ==> 1.1.alpha19
treepl : 2018.05.22 ==> 2020-02-14
trimadap : 0.1.11 ==> 0.1.11
varscan : 2.4.3 ==> 2.4.4
</pre>
</td>
</tr></table>
> various formulae: add livecheck (part 2)

- Formula/seqkit.rb
> seqkit-0.15.0

- Formula/tigmint.rb
> tigmint 1.2.2

- Formula/jmol.rb
> jmol: test for java.awt.HeadlessException

- Formula/wiggletools.rb
-----
https://github.com/brewsci/homebrew-bio/commit/53ed39b33c3e30f09fdd2e86f417ea66cf14ca1b failed to upload the bottles for https://github.com/brewsci/homebrew-bio/pull/1238, so let's rebuild them
> wiggletools: rebuild bottles

- Formula/taxonkit.rb
> taxonkit-0.7.1

- Formula/gfaview.rb
-----
Repository https://github.com/lh3/gfa1 is archived
> gfaview: deprecate

- Formula/taxonkit.rb
> taxonkit-0.7.2

- Formula/kat.rb
- Formula/matplotlib.rb
partially supersedes #1174 
-----
> matplotlib 3.3.4

- Formula/slim.rb
-----
SLiM is an evolutionary simulation framework that combines a powerful engine for population genetic simulations with the capability of modeling arbitrarily complex evolutionary scenarios.
> slim v3.5 (new formula)

- Formula/ntjoin.rb
> ntjoin 1.0.6

- Formula/bali-phy.rb
> bali-phy 3.6.0

- Formula/falco.rb
> falco 0.2.4 (new formula)

- Formula/abyss-explorer.rb
- Formula/jmol.rb
- abyss-explorer: Use HOMEBREW_GITHUB_ACTIONS
- jmol: Use HOMEBREW_GITHUB_ACTIONS
> Use HOMEBREW_GITHUB_ACTIONS rather than CI

- Formula/raster3d.rb
-----
Raster3D 3.0-7 for macOS
> raster3d 3.0-7 (new formula)

- Formula/mmdb2.rb
-----
C++ toolkit for working with macromolecular coordinate files. This is a component of libccp4, libssm, clipper, or Coot.
> mmdb2 2.0.20 (new formula)

- Formula/astral.rb
- Formula/biomake.rb
- Formula/bioperl.rb
- Formula/fasttree.rb
- Formula/minimap2.rb
- Formula/mummer.rb
- Formula/nextflow.rb
- Formula/snpeff.rb
- Formula/trimadap.rb
- astral
- biomake
- bioperl
- fasttree
- minimap2
- mummer
- nextflow
- snpeff
- trimadap
> Fix style: Ambiguous regexp literal

- .github/workflows/upload-bottles.yml
> Upload bottles to Archive.org

- .github/ISSUE_TEMPLATE.md
- .github/workflows/build-bottles.yml
- .github/workflows/upload-bottles.yml
- Formula/dsh-bio.rb
- LICENSE
- Makefile
- README.md
- _config.yml
- upload-bottles.yml: Change -- to - in the filename
- dsh-bio: Change root_url
- build-bottles.yml: Change root-url to Archive.org
- Change Linuxbrew to Homebrew
> Change root-url to Archive.org

- .github/workflows/build-bottles.yml
- .github/workflows/upload-bottles.yml
-----
Blocked by PR https://github.com/Homebrew/brew/pull/10677
> CI: Upload bottles to Archive.org using pr-upload

- Formula/clipper4coot.rb
-----
add `--enable-shared` option for building coot.
> clipper4coot: add enable-shared

- Formula/fastani.rb
> fastani: gzip test data

- Formula/flye.rb
> flye 2.8.3

- Formula/flye.rb
-----
See https://github.com/brewsci/homebrew-bio/pull/1315#issuecomment-804488855
> flye: Update the description from upstream

- Formula/krona.rb
> krona 2.8 (new formula)

- Formula/nanofilt.rb
> nanofilt 2.8.0

- .github/workflows/build-bottles.yml
- .github/workflows/upload-bottles.yml
> CI: Upload bottles to GitHub Packages

- .github/workflows/upload-bottles.yml
> CI: Set HOMEBREW_FORCE_HOMEBREW_ON_LINUX=1

- .github/workflows/upload-bottles.yml
-----
Update Homebrew for the newest version of `github_packages.rb`.
> CI: Run brew update

- Formula/uniqtag.rb
> uniqtag: README.md is installed automatically

- Formula/taxonkit.rb
-----
Update TaxonKit to 0.8.0
> taxonkit-0.8.0

- Formula/hh-suite.rb
-----
For some reason the gcc based binaries are really slow when we tried them. I updated the recipe to correctly use clang with openmp and while doing that generally modernized the recipe.
> hh-suite: use clang, add test, add arm64, drop unsupported scripts

- Formula/seqkit.rb
> update seqkit to 0.16.0

- Formula/ntedit.rb
> ntedit 1.3.5

- Formula/alevin-fry.rb
https://github.com/COMBINE-lab/alevin-fry/
> alevin-fry 0.3.0 (new formula)

- Formula/seqan@3.rb
> seqan@3 3.0.3

- Formula/phyx.rb
> phyx 1.2.1

- Formula/pathvisio.rb
> pathvisio: Update the description

- Formula/arcs.rb
> arcs 1.2.2

- Formula/tigmint.rb
> tigmint 1.2.3

- Formula/ntjoin.rb
> ntjoin 1.0.7

- Formula/ntlink.rb
> ntlink 1.0.1 (new formula)

- Formula/phylonium.rb
-----
People asked me for a homebrew version so I tried my best to create a formula. Let me know if I did some thing terribly wrong, but it seems to work fine on my mac.
> phylonium 1.5 (new formula)

- Formula/jmol.rb
https://github.com/brewsci/homebrew-bio/pull/1386
CC @sjackman
> Fix jmol 14.31.49 SHA-256 checksum

- Formula/rasusa.rb
> rasusa 0.4.1

- Formula/kalign.rb
- [ x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?
-----
> kalign 3.3.1

- .github/workflows/build-bottles.yml
> [FIX] Missing permissions in CI

- .github/workflows/build-bottles.yml
- Formula/raptor.rb
> raptor 2.0.0

- .github/workflows/build-bottles.yml
- Formula/dssp.rb
-----
Add license info to dssp and fix CI
> add license to dssp

- tap_migrations.json
> mrbayes: migrate to core

- Formula/pymol.rb
-----
upgrade to version 2.5.0.
> pymol 2.5.0

- Formula/rasusa.rb
> update rasusa to 0.6.0

- Formula/kollector.rb
> kollector: import from brewsci/science

- Formula/autodock-vina.rb
-----
New formula to install Autodock Vina 1.2.2. https://github.com/ccsb-scripps/AutoDock-Vina/
> autodock-vina 1.2.2 (new formula)

- Formula/arcs.rb
-----
```
Formula/arcs.rb:31:5: C: [Corrected] Don't use 'on_macos' in 'def install', use 'if OS.mac?' instead.
on_macos do
^^^^^^^^
```
> arcs: Fix style

- Formula/bmdca.rb
-----
```
Formula/bmdca.rb:31:5: C: [Corrected] Don't use 'on_macos' in 'def install', use 'if OS.mac?' instead.
on_macos do
^^^^^^^^
```
> bmdca: Fix style

- Formula/phyx.rb
-----
```
Formula/phyx.rb:24:7: C: [Corrected] Don't use 'on_linux' in 'def install', use 'if OS.linux?' instead.
on_linux do
^^^^^^^^
```
> phyx: Fix style

- Formula/mrbayes.rb
-----
```
Formula/mrbayes.rb:27:13: W: [Corrected] Wrap expressions with varying precedence with parentheses to avoid ambiguity.
args << "--with-mpi=" + (build.with?("open-mpi") ? "yes" : "no")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
> mrbayes: Fix style

- Formula/berokka.rb
> berokka: Use homebrew/core/bioperl

- Formula/berokka.rb
> berokka: Bump revision for homebrew/core/bioperl

- Formula/velvetoptimiser.rb
> velvetoptimiser: Use homebrew/core/bioperl

- Formula/simulate-pcr.rb
> simulate-pcr: Use homebrew/core/bioperl

- Formula/roary.rb
- Formula/simulate-pcr.rb
> roary: Use homebrew/core/bioperl

- Formula/maxbin2.rb
> maxbin2: Use homebrew/core/bioperl

- Formula/pirate.rb
> pirate: Use homebrew/core/bioperl

- Formula/ntjoin.rb
> ntjoin 1.0.8

- .github/workflows/build-bottles.yml
-----
See https://github.com/actions/virtual-environments/issues/4060
> CI: Build bottles on macOS 10.15 Catalina

- Formula/ntlink.rb
> ntlink 1.1.1

- Formula/tmalign.rb
-----
update tmalign to the latest commit.
> tmalign 20210527

- Formula/gemmi.rb
> gemmi 0.4.9 (new formula)

- Formula/psdm.rb
> add psdm recipe

- Formula/fpocket.rb
> Add fpocket (new formula)

- Formula/tigmint.rb
> tigmint 1.2.5

- Formula/seqan@3.rb
> seqan3 3.1.0

- Formula/mustang.rb
-----
Mustang 3.2.3 (new formula).
> mustang 3.2.3 (new formula)

- Formula/hh-suite.rb
-----
Fix an issue of installation on M1 Mac.
> HH-suite: fix for M1 Mac

- Formula/ntlink.rb
> ntlink 1.1.2

- Formula/libccp4.rb
> libccp4: update for M1 Mac (issue #1450)

- Formula/arcs.rb
> arcs 1.2.3

- Formula/maxit.rb
> maxit: fix missing odb files again

- Formula/jmol.rb
> jmol 14.32.44

- Formula/kalign.rb
> kalign 3.3.2

- Formula/ntlink.rb
> ntlink 1.1.3

- Formula/libccp4.rb
> libccp4: remove xcode dependency

- Formula/clipper4coot.rb
> clipper4coot: hack for M1 Mac

- Formula/ssm.rb
> ssm: add --enable-shared for coot

- .github/workflows/build-bottles.yml
- Formula/bowtie.rb
also test bottling workflow change
-----
> bowtie 1.3.1

- Formula/tabixpp.rb
> tabixpp 1.1.1 (new formula)

- Formula/vcflib.rb
> vcflib: fixed build on arm64

- Formula/links-scaffolder.rb
> links-scaffolder 2.0.1

- Formula/fastahack.rb
> fastahack 1.0.0 (new formula)

- Formula/freebayes.rb
> freebayes 1.3.6

- Formula/apbs.rb
-----
(again) Formula of APBS, which is widely used in the field of structural biology.
> apbs 3.4.0 (new formula)

- Formula/minimap2.rb
> minimap2: fix m1 compiling issue

- Formula/ntlink.rb
> ntlink 1.2.1

- Formula/btllib.rb
> btllib 1.4.4 (new formula)

- Formula/pymol.rb
-----
update dependencies for pymol to use the latest pyqt and python-tk.
> pymol: update dependencies

- Formula/gemmi.rb
-----
Update to version 0.5.6.
> gemmi 0.5.6

- Formula/pymol.rb
-----
Update to be compatible with python 3.10. Newly add `--openmp=yes`.
> pymol: update to python 3.10

- .github/workflows/build-bottles.yml
> Upgrade deprecated GitHub-hosted runners

- Formula/emboss.rb
> Use postgresql@14 as optional dependency

- Formula/rasusa.rb
> update rasusa to version 0.7.0

- Formula/dssp.rb
-----
https://github.com/brewsci/homebrew-science/pull/303
> dssp 4.0.3

- Formula/iva.rb
> iva: revision for python

- Formula/btllib.rb
> btllib 1.4.8

- .github/workflows/upload-bottles.yml
-----
Per https://github.com/actions/runner-images/issues/6283
> CI: shellenv Linuxbrew

- Formula/ntlink.rb
> ntlink 1.3.4

- Formula/trf.rb
> trf 4.09.1

- .github/workflows/build-bottles.yml
- Formula/repeatmasker.rb
> repeatmasker 4.1.3

- Formula/repeatmasker.rb
-----
Mostly to rebuild the bottle.
> repeatmasker: tweak wording

- Formula/usalign.rb
-----
USalign: Universal structure alignment of monomeric and complex proteins and nucleic acids
GitHub: https://github.com/pylelab/USalign
Paper: https://doi.org/10.1038/s41592-022-01585-1
> USalign 20220924 (new formula)

- Formula/dssp.rb
-----
- `install_prefix` should be `prefix/"libcifpp"` to make the dic file `mmcif_pdbx_v50.dic` accessible after installation.
- `boost` should not be build-only for Linux.
> dssp 4.0.5

- Formula/bam2fastx.rb
> bam2fastx 1.3.1

- Formula/treepl.rb
> treepl 2022.04.06

- Formula/relion.rb
-----
Add [Relion 4.0.0](https://github.com/3dem/relion) formula for structural biology community.
> relion 4.0.0 (new formula)

- Formula/breseq.rb
> breseq 0.37.1

- Formula/gemmi.rb
> gemmi 0.6.2

- Formula/dssp.rb
> dssp 4.4.0

- Formula/libzeep.rb
> libzeep 6.0.1 (new formula)

- Formula/libcifpp.rb
> libcifpp 5.1.1 (new formula)

- Formula/bali-phy.rb
- Formula/cluster-picker.rb
- Formula/ema.rb
- Formula/gepard.rb
- Formula/r2r.rb
> use https:// in homepage url

- Formula/bali-phy.rb
- Formula/cluster-picker.rb
- Formula/ema.rb
- Formula/falco.rb
- Formula/gepard.rb
- Formula/r2r.rb
> falco 1.2.1

- Formula/kaiju.rb
> kaiju 1.9.2

- Formula/btllib.rb
> btllib 1.6.2

- Formula/ntlink.rb
> ntlink 1.3.9

- Formula/relion.rb
> relion 4.0.1

- Formula/foldseek.rb
> foldseek 8-ef4e960 (new formula)

- Formula/oma.rb
> bump oma 2.6.0

- Formula/gemmi.rb
> gemmi 0.6.3

- Formula/autodock-vina.rb
> autodock vina 1.2.5

- Formula/bali-phy.rb
> bali-phy: 4.0-beta7

- Formula/gemmi.rb
> gemmi 0.6.4

- Formula/salmon.rb
> salmon 1.10.1

- Formula/gemmi.rb
> gemmi 0.6.5

- Formula/iqtree2.rb
> iqtree2 2.3.3

- Formula/bali-phy.rb
> bali-phy: 4.0-beta9

- Formula/hmmer@2.rb
> hmmer@2 2.3.2

- Formula/meme.rb
> meme 5.5.5

- Formula/meme@4.rb
> meme@4 4.12.0

- Formula/hmmer@2.rb
> hmmer@2: keg_only

- Formula/hmmer@2.rb
> hmmer@2: rename man commands

- Formula/meme@4.11.2.rb
> meme@4.11.2

- Formula/meme@4.11.2.rb
> meme@4.11.2: fix url

- Formula/meme@4.11.2.rb
> meme@4.11.2: fails_with gcc-5

- Formula/hh-suite.rb
> hh-suite: fix an error of "'ptr_fun' in namespace 'std'"

- Formula/foldseek.rb
> foldseek: 9-427df8a

- Formula/seqerr.rb
> seqerr r1181

- Formula/ibdseq.rb
> ibdseq r1206

- Formula/bali-phy.rb
> bali-phy: 4.0-beta12

- Formula/bali-phy.rb
> bali-phy: 4.0-beta13

- Formula/kissplice.rb
-----
Upstream fix to path computations when main binary is symlinked.
> kissplice 2.6.7

- Formula/hap-ibd.rb
> hap-ibd 1.0.0

- .github/workflows/build-bottles.yml
- .github/workflows/upload-bottles.yml
This is an attempt to fix the shellcheck failures in #1703
There is one "style" issue left that I'm not sure can be fixed.
> Fix shellcheck failures

- Formula/gemmi.rb
> gemmi 0.6.6

- Formula/edirect.rb
> edirect 22.1

- Formula/dssp.rb
> dssp 4.4.7

- Formula/hmmer@2.rb
> hmmer@2: re-bottle

- Formula/mmdb2.rb
> mmdb2 2.0.22

- Formula/meme@4.11.2.rb
> meme@4.11.2: re-bottle

- Formula/glimmerhmm.rb
> glimmerhmm: re-bottle

- Formula/exonerate.rb
> exonerate: re-bottle

- Formula/fasttree.rb
> fasttree: re-bottle

- Formula/raster3d.rb
> raster3d: re-bottle

- Formula/iqtree2.rb
> iqtree 2.3.5

- Formula/rmblast.rb
> rmblast 2.14.1

- Formula/trf.rb
> trf: re-bottle

- Formula/usalign.rb
> usalign 20240706

- Formula/relion.rb
> relion: re-bottle

- Formula/mcl.rb
> mcl 22-282

- Formula/kaiju.rb
> kaiju 1.10.1

- Formula/infernal.rb
> infernal 1.1.5

- Formula/aragorn.rb
> aragorn 1.2.41

- Formula/barrnap.rb
> barrnap: re-bottle

- Formula/cd-hit.rb
> cd-hit: re-bottle

- Formula/minced.rb
> minced: re-bottle

- Formula/star-aligner.rb
> star-aligner 2.7.11b

- Formula/gatk.rb
> gatk 4.6.0.0

- Formula/pirate.rb
> pirate 1.0.5

- Formula/harvest-tools.rb
> harvest-tools 1.3

- Formula/salmon.rb
> salmon: re-bottle

- Formula/kraken2.rb
> kraken2 2.1.3

- Formula/libccp4.rb
> libccp4: re-bottle

- Formula/germline2.rb
> germline2 1.0 (new formula)

- Formula/clipper4coot.rb
> clipper4coot: re-bottle

- Formula/ssm.rb
> ssm: re-bottle

- Formula/prank.rb
> prank: re-bottle

- Formula/fastani.rb
> fastani 1.34

- Formula/express.rb
> express: re-bottle

- Formula/trimmomatic.rb
> trimmomatic: re-bottle

- Formula/trinity.rb
-----
Use libomp and Apple clang to compile source codes.
> trinity 2.15.1

- Formula/prokka.rb
> prokka: re-bottle

- Formula/stringtie.rb
> stringtie 2.2.3

- Formula/transdecoder.rb
> Transdecoder 5.7.1

- Formula/coot.rb
> Coot 1.1.09 (new formula)

- Formula/parsnp.rb
> parsnp 2.0.5

- Formula/coot.rb
> Coot 1.1.10

- Formula/viennarna.rb
> ViennaRNA 2.6.4

- Formula/alevin-fry.rb
> alevin-fry 0.10.0

- Formula/salmon.rb
> salmon 1.10.3

- Formula/bali-phy.rb
> bali-phy: 4.0-beta15

- Formula/bowtie.rb
> bowtie: rebuild bottle

- Formula/hisat2.rb
> hisat2: build bottle for ARM64

- Formula/apbs.rb
> APBS 3.4.1

- Formula/apbs.rb
> apbs: add dependencies

- Formula/apbs.rb
> apbs: add tools

- Formula/seqan@2.rb
> seqan@2: rebuild bottle

- Formula/maxit.rb
> maxit 11.200

- Formula/repeatmasker.rb
> repeatmasker 4.1.6

- Formula/phylonium.rb
> phylonium 1.7

- Formula/reduce.rb
> Reduce 4.14  (new formula) 

- Formula/bwa-mem2.rb
> bwa-mem2 2.2.1

- Formula/ntlink.rb
> ntlink 1.3.10

- Formula/btllib.rb
> btllib 1.7.3

- Formula/nthits.rb
> nthits 1.0.3

- Formula/ntedit.rb
> ntedit 2.0.2

- Formula/ntedit.rb
> ntedit: add xcode dep

- Formula/tantan.rb
> tantan 50 (new formula)

- Formula/vcflib.rb
> vcflib 1.0.10

- Formula/freebayes.rb
> freebayes 1.3.6: revision 1

- Formula/ntlink.rb
> ntlink: rebuild

- Aliases/eig
- Formula/eigensoft.rb
> eigensoft 8.0.0 (new formula)

- Formula/antismash.rb
> antismash 7.1.0.1 (new formula)

- Formula/samclip.rb
> samclip 0.4.0: rebuild

- Formula/snp-sites.rb
> snp-sites: rebuild

- Formula/snpeff.rb
> snpeff: rebuild

- Formula/plink2.rb
> plink2 2.00a5.12

- Formula/meme.rb
> meme 5.5.6

- Formula/parasail.rb
> parasail 2.6.2

- Formula/links-scaffolder.rb
> Links-scaffolder: rebuild

- Formula/arcs.rb
> arcs 1.2.7

- Formula/racon.rb
> racon 1.5.0

- Formula/unicycler.rb
> unicycler 0.5.1

- Formula/quast.rb
> quast 5.2.0

- Formula/cutadapt.rb
> cutadapt 4.9

- Formula/vt.rb
> vt 0.57721

- Formula/libzeep.rb
> libzeep 6.0.13

- Formula/libcifpp.rb
> libcifpp 7.0.4

- Formula/libmcfp.rb
> libmcfp 1.3.3

- Formula/hh-suite.rb
> hh-suite: include scripts directory

- Formula/centrifuge.rb
> centrifuge 1.0.4.1

- Formula/bustools.rb
> bustools 0.43.2 (new formula)

- Formula/bifrost.rb
> bifrost 1.3.5

- Formula/mummer.rb
> mummer 4.0.0rc1

- Formula/circlator.rb
> circlator 1.5.5

- Formula/clustal-w.rb
> clustal-w 2.1: rebuild

- Formula/emboss.rb
> emboss 6.6.0: rebuild

- Formula/clustal-omega.rb
> clustal-omega 1.2.4: rebuild

- Formula/smalt.rb
> smalt 0.7.6: rebuild

- Formula/relion.rb
> relion 4.0.2

- Formula/lighter.rb
- Formula/shovill.rb
> lighter 1.1.3

- Formula/kma.rb
> kma 1.4.15

- Formula/libsbml.rb
> libsbml 5.20.4

- Formula/porechop.rb
> porechop 0.2.4: rebuild

- Formula/breseq.rb
> breseq 0.39.0

- Formula/gffcompare.rb
> gffcompare 0.12.6

- Formula/libbigwig.rb
> libbigwig 0.4.7

- Formula/wiggletools.rb
> wiggletools 1.2.11

- Formula/slim.rb
> slim 4.2.2

- Formula/gffread.rb
> gffread 0.12.7: rebuild

- Formula/eastr.rb
> eastr 1.0 (new formula)

- Formula/oarfish.rb
> oarfish 0.6.2 (new formula)

- Formula/sequencetools.rb
> sequencetools 1.5.4.0

- Formula/ntsynt.rb
> ntsynt 1.0.2 (new formula)

- Formula/d4tools.rb
> d4tools 0.3.10 (new formula)

- Formula/mosdepth.rb
> mosdepth 0.3.9

- Formula/gemmi.rb
> gemmi 0.6.7

- Formula/coot.rb
> Coot: rebuild

- Formula/mashmap.rb
> mashmap 3.1.3 (new formula)

- Formula/harvest-tools.rb
> harvest-tools: rebuild

- Formula/express.rb
> express: rebuild

- Formula/alfred.rb
> alfred 0.3.2 (new formula)

- Formula/delly.rb
> delly 1.2.8

- Formula/libcuemol2.rb
> libcuemol2 2024.09.21 (new formula)

- Formula/percolator.rb
> percolator 3.7.1

- Formula/mview.rb
> MView 1.68 (new formula)

- Formula/autoconf@2.13.rb
-----
autoconf@2.13 is required for some old packages.
> autoconf@2.13 (new formula)

- Formula/metabuli.rb
> metabuli 1.0.8 (new formula)

- Formula/edirect.rb
> edirect 22.7

- Formula/edirect.rb
> edirect 22.8

- Formula/coot.rb
> coot: add 'coordgen' dependency and a patch

- Formula/gemmi.rb
> gemmi: support Sequoia

- Formula/mmdb2.rb
> mmdb2: support Sequoia

- Formula/raster3d.rb
> raster3d: support Sequoia

- Formula/libccp4.rb
> libccp4: support Sequoia

- Formula/ssm.rb
> ssm: support Sequoia

- Formula/clipper4coot.rb
> clipper4coot: support Sequoia

- Formula/libcifpp.rb
> libcifpp: support Sequoia

- Formula/libmcfp.rb
> libmcfp: support Sequoia

- Formula/coot.rb
> coot: support Sequoia

- Formula/salmon.rb
> salmon: support Sequoia

- Formula/express.rb
> express: support Sequoia

- Formula/libzeep.rb
> libzeep: support Sequoia

- Formula/stringtie.rb
> stringtie: support Sequoia

- Formula/veryfasttree.rb
> veryfasttree: support Sequoia

- Formula/apbs.rb
> apbs: support Sequoia

- Formula/harvest-tools.rb
> harvest-tools: support Sequoia

- Formula/d4tools.rb
> d4tools: support Sequoia

- Formula/phylonium.rb
> phylonium: support Sequoia

- Formula/bustools.rb
> bustools: support Sequoia

- Formula/gatk.rb
> gatk: support Sequoia

- Formula/delly.rb
> delly 1.3.1

- Formula/clustal-w.rb
> clustal-w: support Sequoia

- Formula/cd-hit.rb
> cd-hit: support Sequoia

- Formula/mosdepth.rb
> mosdepth: support Sequoia

- Formula/minced.rb
> minced: support Sequoia

- Formula/smalt.rb
> smalt: support Sequoia

- Formula/clustal-omega.rb
> clustal-omega: support Sequoia

- Formula/centrifuge.rb
> centrifuge: support Sequoia

- Formula/alphafill.rb
> alphafill: support Sequoia

- Formula/alevin-fry.rb
> alevin-fry: support Sequoia

- Formula/aragorn.rb
> aragorn: support Sequoia

- Formula/autodock-vina.rb
> autodock-vina: support Sequoia

- Formula/alfred.rb
> alfred: support Sequoia

- Formula/eigensoft.rb
> eigensoft: support Sequoia

- Formula/exonerate.rb
> exonerate: support Sequoia

- Formula/emboss.rb
> emboss: support Sequoia

- Formula/iqtree2.rb
> iqtree2 2.3.6

- Formula/falco.rb
> falco: support Sequoia

- Formula/kaiju.rb
> kaiju: support Sequoia

- Formula/infernal.rb
> infernal: support Sequoia

- Formula/libcifpp.rb
> libcifpp 7.0.7

- Formula/dssp.rb
> dssp 4.4.10

- Formula/ema.rb
> ema: support Sequoia

- Formula/gffread.rb
> gffread: support Sequoia

- Formula/libsbml.rb
> libsbml: support Sequoia

- Formula/ntedit.rb
> ntedit: support Sequoia

- Formula/bifrost.rb
> bifrost: support Sequoia

- Formula/qtltools.rb
> qtltools: support Sequoia

- Formula/relion.rb
> relion: support Sequoia

- Formula/foldseek.rb
> foldseek: support Sequoia

- Formula/maxit.rb
> maxit: support Sequoia

- Formula/sequencetools.rb
> sequencetools: support Sequoia

- Formula/oarfish.rb
> oarfish: support Sequoia

- Formula/hyphy.rb
> hyphy 2.5.63 (new formula)

- Formula/germline2.rb
> germline2: support Sequoia

- Formula/mustang.rb
> mustang: support Sequoia

- Formula/meme.rb
> meme 5.5.7

- Formula/fasttree.rb
> fasttree: support Sequoia

- Formula/muscle.rb
> muscle: support Sequoia

- Formula/hmmer@2.rb
> hmmer@2: support Sequoia

- Formula/meme@4.11.2.rb
> meme@4.11.2: support Sequoia

- Formula/libcifpp.rb
> libcifpp 7.0.8

- Formula/usalign.rb
> usalign 20241114

- Formula/gemmi.rb
> gemmi 0.7.0

- Formula/gtk4@4.14.rb
> gtk4@4.14 4.14.5 (new formula)

- Formula/coot.rb
> coot 1.1.11

- Formula/coot.rb
> Coot 1.1.11 Rev. 2

- Formula/libpll.rb
> libpll 0.4.0

- Formula/edirect.rb
> edirect 23.3

- Formula/stringtie.rb
> stringtie 3.0.0

- Formula/bali-phy.rb
> bali-phy: 4.0-beta17

- Formula/coot.rb
> coot 1.1.12

- Formula/coot.rb
> Coot 1.1.13

- Formula/seqan@3.rb
> seqan3 3.3.0

- Formula/seqan@2.rb
> seqan2 2.5.0

- Formula/bali-phy.rb
> bali-phy: 4.0

- Formula/coot.rb
> coot 1.1.14

- Formula/gemmi.rb
> gemmi 0.7.1

- Formula/reduce.rb
> reduce 4.15

- Formula/pygobject3@3.50.rb
> pygobject3@3.50 (new formula)

- Formula/rdock.rb
> rdock v24.04.204-legacy (new formula)

- Formula/pygobject3@3.50.rb
- Formula/rdock.rb
> pygobject3@3.50: add python3.13

- Formula/autodock-vina.rb
> autodock-vina 1.2.7

- Formula/coot.rb
-----
This PR is not perfect but for testing.
> coot: use python3.13 and pygobject3.50

- Formula/usalign.rb
> usalign 20241201

- Formula/maxit.rb
> maxit v11.300

- Formula/mosdepth.rb
> mosdepth 0.3.11

- Formula/parasail.rb
> parasail: support Sequoia

- Formula/smina.rb
> smina (new formula)

- Formula/antismash.rb
> antismash: support Sequoia

- Formula/bustools.rb
> bustools 0.45.0

- Formula/edirect.rb
> edirect 23.8

- Formula/antismash.rb
> antismash 8.0.0

- Formula/openmm@7.rb
> openmm@7 7.7.0 (new formula)

- Formula/voronota.rb
> voronota: Enable OpenMP support

- Formula/oarfish.rb
> oarfish 0.8.1

- Formula/openstructure.rb
- Replaced sip4 with the latest version of sip from homebrew-core, since it was found to be buildable with sip6 instead of sip4.
- Enabled tmtools because tmalign of the fortran version is required to use the align function on dng (GUI).
---
This pull request updates the `Formula/openstructure.rb` file to modify dependencies, build configurations, and testing steps for the OpenStructure formula. The key changes include adjustments to dependencies, enabling additional build features, and adding a testing step during the build process.
* Added `gcc` as a build dependency and replaced `brewsci/bio/sip@4` and `brewsci/bio/usalign` with `sip`. (`[[1]](diffhunk://#diff-bec696567eb9cc30ed32151e2c39b1adddd4ce6d25c23c588e9e89e6671bb997R21-L29)`, …
> openstructure:  Enable tmtools and organize dependencies

- Formula/lsd2.rb
> lsd2 2.4.1

- Formula/kraken2.rb
> kraken2 2.1.5

- Formula/lighter.rb
> lighter: support Sequoia

- Formula/promod3.rb
> promod3 (new formula)

- Formula/qmean.rb
> qmean (new formula)

- Formula/msms.rb
> msms (new formula)

- Formula/freesasa.rb
> freesasa (new formula)

- Formula/qmean.rb
> qmean: Bump up openstructure to v2.10.0

- Formula/qmean.rb
> qmean: Add `rebuild 1`

- Formula/promod3.rb
> promod3: Bump up openstructure to v2.10.0

- Formula/freesasa.rb
> freesasa: Fix Makefile replacement condition for Linux build on HEAD

- Formula/antismash.rb
> antismash 8.0.1

- Formula/ssm.rb
> ssm: rebuild

- Formula/clipper4coot.rb
> clipper4coot: rebuild

- Formula/qmean.rb
> qmean 4.4.0 (rebuild)

- Formula/bali-phy.rb
> bali-phy 4.1

- Formula/newick-utils.rb
> Fix newick utils

- Formula/promod3.rb
> promod3: Rebuild

- Formula/libmcfp.rb
> libmcfp v1.4.2

- Formula/fasta.rb
> Update fasta 36.3.8i_Nov2022

- Formula/openms.rb
> Add openms

- Formula/edirect.rb
> edirect 24.7

- Formula/libccp4.rb
> libccp4: add tahoe

- Formula/pygobject3@3.50.rb
> pygobject3@3.50: add tahoe

- Formula/coot.rb
> coot: add tahoe

- Formula/clustal-omega.rb
> clustal-omega: add tahoe

- Formula/bustools.rb
> bustools 0.45.1

- Formula/apbs.rb
> apbs: add tahoe

- Formula/alevin-fry.rb
> alevin-fry: 0.11.2

- Formula/parasail.rb
> parasail: add tahoe

- Formula/lsd2.rb
> lsd2: add tahoe

- Formula/openmm@7.rb
> openmm@7: add tahoe
